-- ALTER TABLE beneficiary DROP CONSTRAINT beneficiaryId;
-- ALTER TABLE project DROP CONSTRAINT projectId;
-- ALTER TABLE org DROP CONSTRAINT orgId;
-- ALTER TABLE user DROP CONSTRAINT userId;





DROP TABLE IF EXISTS demographic;
DROP TABLE IF EXISTS beneficiary;
DROP TABLE IF EXISTS org_user;
DROP TABLE IF EXISTS project_user;
DROP TABLE IF EXISTS indicator;
DROP TABLE IF EXISTS impact;
DROP TABLE IF EXISTS outcome;
DROP TABLE IF EXISTS project;
DROP TABLE IF EXISTS org;

-- DROP TABLE IF EXISTS user;

