DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS project;
DROP TABLE IF EXISTS org;
DROP TABLE IF EXISTS orgUser;
DROP TABLE IF EXISTS projectUser;
DROP TABLE IF EXISTS beneficiary;
DROP TABLE IF EXISTS demographic;