-- ALTER TABLE beneficiary DROP CONSTRAINT beneficiaryId;
-- ALTER TABLE project DROP CONSTRAINT projectId;
-- ALTER TABLE org DROP CONSTRAINT orgId;
-- ALTER TABLE user DROP CONSTRAINT userId;





DROP TABLE IF EXISTS demographic;
DROP TABLE IF EXISTS beneficiary;
DROP TABLE IF EXISTS projectUser;
-- DROP TABLE IF EXISTS orgUser;
-- DROP TABLE IF EXISTS project;
-- DROP TABLE IF EXISTS org;
-- DROP TABLE IF EXISTS user;

